on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get_RELEASE_VERSION
        run:
          echo "${{env.RELEASE_VERSION}}"
      - name: ${{env.RELEASE_VERSION}}-docs.tar.gz
        run:
          tar -czvf ${{env.RELEASE_VERSION}}-docs.tar.gz ./pages/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{env.RELEASE_VERSION}}-docs.tar.gz
          path: ${{env.RELEASE_VERSION}}-docs.tar.gz
          retention-days: 1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync ${{env.RELEASE_VERSION}}-docs.tar.gz s3://peiyi-static-website
